package com.everyTing.core.notification.domain;

public enum NotificationType {
    PROFILE_PHOTO_GENERATION_FAILED,
    PROFILE_PHOTO_GENERATION_COMPLETED,
    NEW_TEAM_MEMBER,
    TEAM_MEMBER_EXPELLED,
    TEAM_MEMBER_LEFT,
    TEAM_DATE_MATCHED,
    TEAM_DATE_REQUESTED,
    TEAM_DATE_REQUEST_REJECTED
}
