version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - '3000:3000'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - '9090:9090'
    command:
      - '--web.enable-lifecycle'  # Allows you to reload configuration files without restarting api
      - '--config.file=/etc/prometheus/prometheus.yaml'
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"