name:
  length:
    min: 1
    max: 10

member:
  limit:
    min: 2
    max: 6

hashtag:
  limit:
    max: 7
  content:
    length:
      min: 1
      max: 7

request:
  limit:
    max: 2

regions:
  서울,
  인천,
  경기 남부,
  경기 북부,
  강원,
  충북,
  충남,
  대전,
  세종,
  경북,
  경남,
  부산,
  대구,
  울산,
  전남,
  광주,
  전북,
  제주도