spring:
  datasource:
    url: ${RDB_URL}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
  sql.init.mode: always

