constraint:
  docs:
    name: Team 제약 조건
    url: https://github.com/every-ting/back-end/blob/main/docs/team/Team-Constraints.md
error:
  docs:
    name: Team 에러 코드
    url: https://github.com/every-ting/back-end/blob/main/docs/team/Team-ErrorCode.md

name:
  length:
    min: 3
    max: 20

member:
  limit:
    min: 2
    max: 6

hashtag:
  content:
    length:
      min: 1
      max: 10

regions:
  서울 남부,
  서울 북부,
  인천,
  경기 남부,
  경기 북부,
  강원,
  충북,
  충남,
  대전,
  세종,
  경북,
  경남,
  부산,
  대구,
  울산,
  전남,
  광주,
  전북,
  제주도