spring:
  datasource:
    url: ${RDB_URL}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
  sql.init.mode: always

decorator:
  datasource:
    p6spy:
      enable-logging: false