{
 "title": "dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DataBase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HikariCP Connection Pool",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\"}",
     "legendFormat": "Idle"
    },
    { "expr": "hikaricp_connections_max", "legendFormat": "Max" }
   ]
  },
  {
   "title": "JDBC Connection Pool",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_active{instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "jdbc_connections_idle{instance=\"$instance\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "jdbc_connections_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "HikariCP Pending",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "hikaricp_connections_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "AVG ( HikariCP Connect Acquired Times )",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_sum[1m]) / rate(hikaricp_connections_acquire_seconds_count[1m])",
     "legendFormat": "AVG (time)"
    }
   ]
  },
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Server Up Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"}) / sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed Heap Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"${instance}\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Heap Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Non- Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"}) / sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"nonheap\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed Non-Heap Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"${instance}\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Non-Heap Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SYSTEM CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "system_cpu"
    },
    { "expr": "process_cpu_usage", "legendFormat": "process_cpu" }
   ]
  },
  {
   "title": "PROCESS CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"${instance}\"}",
     "legendFormat": "process-cpu-usage"
    }
   ]
  },
  {
   "title": "Server Threads",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{instance=\"$instance\"}",
     "legendFormat": "current-threads"
    },
    {
     "expr": "tomcat_threads_busy_threads{instance=\"$instance\"}",
     "legendFormat": "running-threads"
    },
    {
     "expr": "tomcat_threads_config_max_threads{instance=\"$instance\"}",
     "legendFormat": "max-threads"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "live-threads"
    },
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\"}",
     "legendFormat": "\bdaemon-threads"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\"}",
     "legendFormat": "peek-threads"
    }
   ]
  },
  {
   "title": "JVM Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "allocated"
    }
   ]
  },
  {
   "title": "DISK USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "disk_total_bytes{instance=\"$instance\"}",
     "legendFormat": "disk_total_bytes"
    },
    {
     "expr": "disk_total_bytes{instance=\"$instance\"} - disk_free_bytes{instance=\"$instance\"}",
     "legendFormat": "disk usage"
    }
   ]
  },
  {
   "title": "HTTP Response & Request Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }
  },
  {
   "title": "Http Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\", uri=~\"/api.*\", status !~\"5..\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG (HTTP API R&T)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=\"$instance\", uri=~\"/api.*\", status !~\"5..\"}[1m])) / sum(rate(http_server_requests_seconds_count{instance=\"$instance\", uri=~\"/api.*\", status !~\"5..\"}[1m]))",
     "legendFormat": "AVG (HTTP API RT)"
    }
   ]
  },
  { "title": "Log Statics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "INFO Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "increase(logback_events_total{instance = \"$instance\", level=\"info\"}[5m])",
     "legendFormat": "info"
    }
   ]
  },
  {
   "title": "ERROR Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "increase(logback_events_total{instance = \"$instance\", level=\"error\"}[5m])",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "DEBUG Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "increase(logback_events_total{instance = \"$instance\", level=\"debug\"}[5m])",
     "legendFormat": "warn"
    }
   ]
  },
  {
   "title": "TRACE Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "increase(logback_events_total{instance = \"$instance\", level=\"trace\"}[5m])",
     "legendFormat": "trace"
    }
   ]
  },
  {
   "title": "WARN Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "increase(logback_events_total{instance = \"$instance\", level=\"warn\"}[5m])",
     "legendFormat": "warn"
    }
   ]
  }
 ]
}