package com.everyTing.notification.domain;

public enum NotificationType {
    PROFILE_PHOTO_GENERATION_FAILED,
    PROFILE_PHOTO_GENERATION_COMPLETED,
    TEAM_DATE_MATCHED,
    TEAM_DATE_REQUEST_REJECTED,
    TEAM_DATE_REQUEST_SUCCESSED
}
