username:
  length:
    min: 2
    max: 8

password:
  pattern: "(?=.*[0-9])(?=.*[a-zA-Z])(?=.*\\W)(?=\\S+$).{9,16}"

email:
  pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$

year:
  limit:
    min: 2010
    max: 1990
