# JWT token cache
jwt:
  secretKey: ThisIsSkeletonCodeOfMeThankYouSoMuch!!

# Key
auth:
  jwt:
    token:
      access:
        key: accessToken
      refresh:
        key: refreshToken

    # Member token payload
    payload:
      key: userId

    # JWT TTL
    access:
      ttl:
        time: 1800 # 30 minutes
      refresh:
        ttl:
          time: 259200 # 3 days
