password:
    encryption:
      algorithm: ${PASSWORD_ENCRYPTION_ALGORITHM}

member:
  encryption:
    algorithm: ${MEMBER_ENCRYPTION_ALGORITHM}
    key:
      algorithm: ${MEMBER_KEY_ALGORITHM}
      value: ${MEMBER_ENCRYPTION_KEY}
