spring.cloud.config.enabled: false

service:
  member:
    name: member-module
    url: ${MEMBER_MODULE_URL}

  team:
    name: team-module
    url: ${TEAM_MODULE_URL}

  notification:
    name: notification-module
    url: ${MEMBER_MODULE_URL}

# feignClient 장애 대비를 위한 env
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000