spring.cloud.config.enabled: false

service:
  member:
    name: member-module
    url: ${MEMBER_MODULE_URL}

  team:
    name: team-module
    url: ${TEAM_MODULE_URL}

  notification:
    name: notification-module
    url: ${MEMBER_MODULE_URL}